### ISSUE TITLE
Mod not properly working on latest

### ISSUE THREAD

**Issue by trevorgolden** [ManindraDeMel/LethalCompanyMoreMoney#1]
Upon updating, the mod no longer works, shows loading in the console, does not give any errors but does not add/set the money upon loading/creating a new save. 

Backdated to the old release of Lethal Company, v40, and mod was still working.

Tried this with BepInEx V5.4.21 and V5.4.22

**Comment by ManindraDeMel** [comment]
This has been resolved in the latest release in this [commit](https://github.com/ManindraDeMel/LethalCompanyMoreMoney/commit/5dd6893ad96fb4573dd5b54f66598b0ae1f3b47f). 

It has also been pushed to thunderstore and R2ModMan
