### ISSUE TITLE
Not work on V49

### ISSUE THREAD

**Issue by HadwinOFE** [ManindraDeMel/LethalCompanyMoreMoney#2]
Not working on latest version(V49)

**Comment by ManindraDeMel** [comment]
> Not working on latest version(V49)

Thank you! Ill have a look into it

**Comment by ManindraDeMel** [comment]
hi just tested on V64 and it seems to work fine.. 
![image](https://github.com/user-attachments/assets/a7913926-da46-4129-aca9-64af7ffcedb5)
(see the screenshot) 

Maybe ill rebuild and reupload to thunderstore..
